-- PROGRAMMERS GROUP BY LEVEL 3 - 조건에 맞는 사용자와 총 거래금액 조회하기
SELECT uu.USER_ID, uu.NICKNAME, SUM(ub.PRICE) AS 'TOTAL_SALES'
FROM USED_GOODS_BOARD ub, USED_GOODS_USER uu
WHERE ub.WRITER_ID = uu.USER_ID AND ub.STATUS = 'DONE'
GROUP BY uu.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES